WIP - DON'T MERGE - Convert to Maven based build
lagom/activator-lagom-java-chirper pull request #52
Opened 2017-04-26 03:43 UTC by fsat

2017-04-26 23:58 UTC, fsat commented
I have performed a manual test on the Chirper frontend using a browser and everything seems to be in working order.

**Scenario: Frontend Usage**

* Start all service using `mvn lagom:runAll`.
* Create a user called `steve`.
* Login as `steve`
* Create a chirp from `steve`: `i am steve`.
* Logout
* Create a user called `jim`.
* Login as `jim`.
* Add `steve` as a friend.
* The chirp `i am steve` is visible for `jim`.
* Logout
* Login as `steve`
* Create a chirp from `steve`: `i like donuts`.
* Logout
* Login as `jim`.
* The chirp `i like donuts` is visible for `jim`.

Throughout the steps above, the page looks correct (i.e. CSS is displayed correctly) and operations are working as expected.

**Scenario: Hot reload JSX**

Modify the `main.jsx` to add an `<h1>` element randomly somewhere on the login page, and it's displayed as expected. When changes are reverted, the page reflects this change accordingly.

The JSX compilation steps adds `2-3` seconds to the hot reloading time.

**Scenario: Hot reload CSS**

Modify the CSS to change the login page banner background to red, and it's working as expected. When changes are reverted, the page reflects this change accordingly.

2017-04-27 02:34 UTC, TimMoore commented
> Due to the different structure between Maven based vs SBT based Play app, it is not possible for SBT and Maven build to co-exist. Because of this the SBT related files are now removed.

@fsat were you thinking this would merge to `master` and replace the SBT version entirely, or remain on a separate branch?

This repo is still an Activator template, and I know Activator is deprecated, but there might still be some people trying to use it that way... plus the name of the repo would be misleading. If we want to have a pure-Maven version, maybe we should push it to a new, separate repo?

2017-04-27 02:49 UTC, TimMoore commented on .travis.yml
> -cache:
It might be a good idea to retain a cache to speed the build: https://docs.travis-ci.com/user/caching#Arbitrary-directories

2017-04-27 02:49 UTC, TimMoore commented on cassandra-config/pom.xml
> +    <artifactId>cassandra-config</artifactId>
I was under the impression that this `cassandra-config` pseudo-project is no longer needed. See https://github.com/lagom/lagom/issues/566

2017-04-27 07:06 UTC, fsat commented on cassandra-config/pom.xml
> +    <artifactId>cassandra-config</artifactId>
Thanks for the catch. I got the `cassandra-config` copied from the Maven archetype, but it's not required. I've tested that signup, login, logout, and chirps are working despite `cassandra-config` being removed.

2017-04-27 07:09 UTC, TimMoore commented on cassandra-config/pom.xml
> +    <artifactId>cassandra-config</artifactId>
Cool, thanks for checking... we're meaning to remove it from the archetype 😄

2017-04-27 07:48 UTC, fsat commented
@jroper and @huntc - I think @TimMoore raised a point about Chirper being part of Activator despite Activator being deprecated, and I'd like to confirm if you think it's better for this PR lives in a separate repo.

Perhaps another alternative is to have a separate branch for maven along side master within `lagom/activator-lagom-java-chirper`

I also have a question about which bundles we should publish (generated by sbt vs maven) given the bundles will have the same name.

Can I ask for your input in this matter please?

2017-04-27 07:50 UTC, fsat commented
Marked as wip - waiting for the answer to https://github.com/lagom/activator-lagom-java-chirper/pull/52#issuecomment-297638682

2017-04-27 09:21 UTC, ignasi35 commented
@fsat I think there's a trick to not discard `sbt` entirely. I learnt from https://github.com/lagom/online-auction-java/pull/78 that disabling `PlayLayoutPlugin` in the `build.sbt` definition of a Play project will make the project fallback to maven-friendly folder structure. See https://github.com/lagom/online-auction-java/pull/78/files#diff-fdc3abdfd754eeb24090dbd90aeec2ceR167

Maybe with a similar trick we can have `mvn` and `sbt` coexisting?

But I'd like @jroper's comment on that, I'm probably missing something.  I'm not sure what are the build requirements for the actual web site (JS compilation, webjars?, etc...) and sbt plugins doing that might not be ready to operate when disabling `PlayLayoutPlugin`.

2017-04-27 10:39 UTC, fsat commented
@ignasi35 - thanks for telling me about `PlayLayoutPlugin`. I'll try this out and put the findings here. 

The only thing that's special with Chirper is the compilation of `.jsx` files which is supported by `sbt-web` on the `sbt` side of the build, and while on the `maven` side I had to use the `frontend-maven-plugin` which supports `node` + `npm` so I can get `node`-based `jsx` compiler installed via `npm.

2017-04-28 00:19 UTC, jroper requested changes
I think you should be able to reinstate sbt support, and disable the PlayLayoutPlugin on the frontend. You'll probably have to move the jsx files to src/main/assets and reconfigure the maven build to handle that, which I guess won't be hard.

2017-04-28 00:19 UTC, jroper commented on .travis.yml
> +  - mvn test -B
You should be able to get travis to do both a Maven and an sbt build:

https://github.com/lagom/online-auction-java/pull/78/commits/55168c943c0eeb690673ba91931126c718d41c8f

2017-04-28 00:19 UTC, jroper commented on build.sbt
> -organization in ThisBuild := "sample.chirper"
As @ignasi35 said, disable the PlayLayoutPlugin, and you should be 90% of the way there to being able to build with either sbt or Maven.

2017-04-28 00:19 UTC, jroper commented on build.sbt
> -organization in ThisBuild := "sample.chirper"
By the way, at some point Play may switch to not enabling the PlayLayoutPlugin by default, so it will be an opt in thing.

2017-04-28 00:22 UTC, jroper commented
To answer the questions:

* We should remove all mentions of Activator from this repo, including changing its name.
* What do you mean which bundles we should publish? A user is either going to use maven or sbt, not both, so it doesn't matter if they both produce bundles with the same name.  And even if they do, the bundles should essentially be equivalent, drop in replacements for each other.

2017-04-28 02:32 UTC, fsat commented
@jroper - I've reinstated the SBT support by disabling the `PlayLayoutPlugin` as both @ignasi35 and yourself suggested.

I kept the assets and public web files on `src/main/resources/assets` and `src/main/resources/public` and pointed `sbt-web` to these directories instead. I know this is different than what you've suggested, but hopefully this is ok.

I've tested the hot reload for both SBT and Maven, and that seems to work with this setup.

I've also reinstated the `sbt test` on Travis similar to what you suggested, and that seemed to work ok.

I'd like to continue with our discussion as well.

> We should remove all mentions of Activator from this repo, including changing its name.

This is removed from the `pom.xml`. Perhaps we can change the name after Activator is removed? I don't think I have permission to change the project.

There's no mention of Activator left in these files:

```
Felixs-MBP-2:activator-lagom-java-chirper felixsatyaputra$ find . -iname "pom.xml" | grep -v "target/" | xargs grep -i "activator"
Felixs-MBP-2:activator-lagom-java-chirper felixsatyaputra$ find . -iname "*.sbt" | grep -v "target/" | xargs grep -i "activator"
Felixs-MBP-2:activator-lagom-java-chirper felixsatyaputra$ find . -iname "*.html" | grep -v "target/" | xargs grep -i "activator"
Felixs-MBP-2:activator-lagom-java-chirper felixsatyaputra$ find . -iname "*.css" | grep -v "target/" | xargs grep -i "activator"
Felixs-MBP-2:activator-lagom-java-chirper felixsatyaputra$ find . -iname "*.js*" | grep -v "target/" | xargs grep -i "activator"
Felixs-MBP-2:activator-lagom-java-chirper felixsatyaputra$ find . -iname "*.java" | grep -v "target/" | xargs grep -i "activator"
Felixs-MBP-2:activator-lagom-java-chirper felixsatyaputra$ find . -iname "*.conf" | grep -v "target/" | xargs grep -i "activator"
```

The only thing left is the `activator.properties`. I think perhaps we should wait until Activator is removed before removing this file.

```
Felixs-MBP-2:activator-lagom-java-chirper felixsatyaputra$ find . -iname "*.prop*" | grep -v "target/" | xargs grep -i "activator"
./activator.properties:authorLogo=http://www.lightbend.com/assets/images/activator/logo-typesafe-activator.png
./activator.properties:sourceLink=https://github.com/lagom/activator-lagom-java-chirper/tree/master
```

> What do you mean which bundles we should publish? A user is either going to use maven or sbt, not both, so it doesn't matter if they both produce bundles with the same name. And even if they do use both, the bundles should essentially be equivalent, drop in replacements for each other.

I agree, they should be equivalent. I guess my question was about whether we prefer sbt vs maven bundle to be published.

But then again after I checked, Chirper bundles are not published to Bintray anyway, so I guess we shouldn't worry about bundles from which build are to be published.

2017-04-28 03:55 UTC, TimMoore commented
Sounds good, @jroper and @fsat. I think we can take care of the repo rename and deletion of `activator.properties` after the deactivation.

Agree that we shouldn't be publishing any artifacts to bintray, so I don't think it's an issue.

2017-04-28 03:57 UTC, TimMoore commented on .travis.yml
> -    - $HOME/.ivy2/cache
I guess we should keep `~/.ivy2/cache` in the Travis cache now that it's a matrix build.

2017-04-28 04:14 UTC, fsat commented on .travis.yml
> -    - $HOME/.ivy2/cache
Thanks for catching this @TimMoore - I missed it when reapplying the sbt build settings to `.travis.yml`.

2017-04-28 04:42 UTC, jroper approved these changes

2017-04-28 04:44 UTC, merged