WIP - DO NOT MERGE - Implement docker support for maven build
lagom/activator-lagom-java-chirper pull request #53
Opened 2017-05-03 19:37 UTC by longshorej

```bash
mvn clean package docker:build
sandbox run 2.1.0-alpha.1

echo "* loading activity-stream"
ACTIVITY_STREAM_ID="$(docker save chirper/activity-stream-impl | bndl --endpoint activity-stream --component oci-image --endpoint akka-remote --component oci-image | conduct load -q)"

echo "* loading chirp"
CHIRP_ID="$(docker save chirper/chirp-impl | bndl --endpoint chirp --component oci-image --endpoint akka-remote --component oci-image | conduct load -q)"

echo "* loading friend"
FRIEND_ID="$(docker save chirper/friend-impl | bndl --endpoint friend --component oci-image --endpoint akka-remote --component oci-image | conduct load -q)"

echo "* loading front-end"
FRONT_END_ID="$(docker save chirper/front-end | bndl --endpoint front-end --component oci-image --endpoint akka-remote --component oci-image | conduct load -q)"

echo "* running activity-stream"
conduct run "$ACTIVITY_STREAM_ID"
echo "* running chirp"
conduct run "$CHIRP_ID"
echo "* running friend"
conduct run "$FRIEND_ID"
echo "* running front-end"
conduct run "$FRONT_END_ID"

```

2017-05-05 07:52 UTC, huntc approved these changes
I'm really liking this...

One consideration: Maven plugins permit configuration to be inherited. You may be able to cut down on the boilerplate for the `docker-maven-plugin` by declaring common configuration in the parent pom. Some of the existing plugins already do that.

2017-05-05 09:29 UTC, markusjura commented
@longshorej Looking good. Note that due to the change in https://github.com/typesafehub/conductr-cli/pull/443 the `--component` argument does not need to be specified anymore.

2017-05-09 18:12 UTC, edwardcallahan requested changes
Review of Deploy.md
 The product name is and some of the early section is again outdated.
 Maven stuff looks good. 
  Should note Docker prereq in Maven section. 
  Consider maven as the default over sbt

2017-05-09 18:12 UTC, edwardcallahan commented on DEPLOY.md
> +[Maven](https://maven.apache.org/) is an another build tool that Lagom Chirper is configured for. If you wish to try out the Maven support, make sure that you've [installed it](https://maven.apache.o
Note Docker requirement in Maven section please

2017-05-09 19:37 UTC, edwardcallahan approved these changes

2017-05-10 22:08 UTC, huntc approved these changes

2017-05-10 22:08 UTC, merged