Build the frontend using webpack
lagom/activator-lagom-java-chirper pull request #64
Opened 2017-06-03 21:31 UTC by benmccann

2017-06-22 03:43 UTC, TimMoore requested changes
I'm not very familiar with webpack, but this seems like a nice improvement to the front-end build.

Sorry that it took so long to review. It looks good other than the SBT issue (which I suppose is just a matter of configuring the [`envVars`](https://github.com/stonexx/sbt-webpack/blob/master/src/main/scala/com/github/stonexx/sbt/webpack/SbtWebpack.scala#L36) setting).

2017-06-22 03:43 UTC, TimMoore commented on front-end/webpack.config.js
> +
I'm getting an error running with SBT:

```
[error] /Users/tmoore/Projects/lagom/activator-lagom-java-chirper/front-end/webpack.config.js:5
[error] const BUILD_DIR = process.env.BUILD_SYSTEM.toLowerCase() === 'maven'
[error]                                           ^
[error] 
[error] TypeError: Cannot read property 'toLowerCase' of undefined
[error]     at Object.<anonymous> (/Users/tmoore/Projects/lagom/activator-lagom-java-chirper/front-end/webpack.config.js:5:43)
[error]     at Module._compile (module.js:569:30)
[error]     at Object.Module._extensions..js (module.js:580:10)
[error]     at Module.load (module.js:503:32)
[error]     at tryModuleLoad (module.js:466:12)
[error]     at Function.Module._load (module.js:458:3)
[error]     at Module.require (module.js:513:17)
[error]     at require (internal/module.js:11:18)
[error]     at /Users/tmoore/Projects/lagom/activator-lagom-java-chirper/front-end/target/webpack/contexts.js:4:19
[error]     at Object.<anonymous> (/Users/tmoore/Projects/lagom/activator-lagom-java-chirper/front-end/target/webpack/contexts.js:18:3)
com.github.stonexx.sbt.webpack.SbtWebpack$NodeExecuteFailureException: Failed to execute node.
	at com.github.stonexx.sbt.webpack.SbtWebpack$.com$github$stonexx$sbt$webpack$SbtWebpack$$runNode(SbtWebpack.scala:247)
	at com.github.stonexx.sbt.webpack.SbtWebpack$$anonfun$getContexts$1.apply(SbtWebpack.scala:141)
	at com.github.stonexx.sbt.webpack.SbtWebpack$$anonfun$getContexts$1.apply(SbtWebpack.scala:135)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (front-end/*:webpack) com.github.stonexx.sbt.webpack.SbtWebpack$NodeExecuteFailureException: Failed to execute node.
```

2017-06-22 03:54 UTC, benmccann commented on front-end/webpack.config.js
> +
Fixed. Thanks for testing it out!

2017-06-22 04:01 UTC, TimMoore commented
Just saw your change, @benmccann ... looks good. I was working on a local fix as well:

```diff
diff --git i/build.sbt w/build.sbt
index 76b012b..c4f7d15 100644
--- i/build.sbt
+++ w/build.sbt
@@ -84,6 +84,8 @@ lazy val frontEnd = project("front-end")
       (sourceDirectory in Assets).value :+
       (resourceDirectory in Assets).value,
 
+    WebpackKeys.envVars in webpack += "BUILD_SYSTEM" -> "sbt",
+
     // Remove to use Scala IDE
     EclipseKeys.createSrc := EclipseCreateSrc.ValueSet(EclipseCreateSrc.ManagedClasses, EclipseCreateSrc.ManagedResources)
   )
```

What do you think? It might be good to be explicit.

I also noticed that there's a v1.2.0 of the sbt plugin that was released since you originally opened this. Do you think it's a good idea to update?

2017-06-22 04:05 UTC, TimMoore approved these changes

2017-06-22 04:06 UTC, TimMoore commented
I've tested locally with both of these changes and it all seems to check out:

```diff
diff --git i/build.sbt w/build.sbt
index 76b012b..c4f7d15 100644
--- i/build.sbt
+++ w/build.sbt
@@ -84,6 +84,8 @@ lazy val frontEnd = project("front-end")
       (sourceDirectory in Assets).value :+
       (resourceDirectory in Assets).value,
 
+    WebpackKeys.envVars in webpack += "BUILD_SYSTEM" -> "sbt",
+
     // Remove to use Scala IDE
     EclipseKeys.createSrc := EclipseCreateSrc.ValueSet(EclipseCreateSrc.ManagedClasses, EclipseCreateSrc.ManagedResources)
   )
diff --git i/front-end/src/main/resources/assets/circuitbreaker.jsx w/front-end/src/main/resources/assets/circuitbreaker.jsx
index 183c122..c52c38c 100644
--- i/front-end/src/main/resources/assets/circuitbreaker.jsx
+++ w/front-end/src/main/resources/assets/circuitbreaker.jsx
@@ -58,13 +58,13 @@ var CircuitBreakerStream = React.createClass({
 		            <table className="invisible-table"><tbody>
 		            <tr><td>
     		            <table><tbody>
-                          <tr><td>State</td><td><CircuitBrakerState state={cb.state}/></td></tr>
-                          <tr><td>Throughput</td><td>{cb.throughputOneMinute.toFixed(0)} msg/s</td></tr>
-                          <tr><td>Failed throughput</td><td>{cb.failedThroughputOneMinute} msg/s</td></tr>
-                          <tr><td>Latency mean</td><td>{formatLatency(cb.latencyMicros.mean)}</td></tr>
-                          <tr><td>Total success count</td><td>{cb.totalSuccessCount}</td></tr>
-                          <tr><td>Total failure count</td><td>{cb.totalFailureCount}</td></tr>
-                          <tr><td>Timestamp</td><td>{cb.timestamp.toFixed(3)}</td></tr>
+                          <tr><th>State</th><td><CircuitBrakerState state={cb.state}/></td></tr>
+                          <tr><th>Throughput</th><td>{cb.throughputOneMinute.toFixed(0)} msg/s</td></tr>
+                          <tr><th>Failed throughput</th><td>{cb.failedThroughputOneMinute} msg/s</td></tr>
+                          <tr><th>Latency mean</th><td>{formatLatency(cb.latencyMicros.mean)}</td></tr>
+                          <tr><th>Total success count</th><td>{cb.totalSuccessCount}</td></tr>
+                          <tr><th>Total failure count</th><td>{cb.totalFailureCount}</td></tr>
+                          <tr><th>Timestamp</th><td>{cb.timestamp.toFixed(3)}</td></tr>
     		            </tbody></table>
     		        </td><td>    
     		            <table><tbody>
diff --git i/project/plugins.sbt w/project/plugins.sbt
index e2ed674..f9fdd06 100644
--- i/project/plugins.sbt
+++ w/project/plugins.sbt
@@ -1,4 +1,4 @@
 addSbtPlugin("com.lightbend.lagom" % "lagom-sbt-plugin" % "1.3.5")
-addSbtPlugin("com.github.stonexx.sbt" % "sbt-webpack" % "1.1.0")
+addSbtPlugin("com.github.stonexx.sbt" % "sbt-webpack" % "1.2.0")
 addSbtPlugin("com.lightbend.conductr" % "sbt-conductr" % "2.3.0")
 addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "5.1.0")
```

For the record, I tested both sbt and Maven, and tested reload-on-change in both with `circuitbreaker.jsx`. Everything works great.

2017-06-22 04:47 UTC, benmccann commented
Those changes seem fine to me!

2017-06-22 05:28 UTC, TimMoore commented
I'm not sure what caused the latest build to fail. I'll try re-running it.

2017-06-22 17:15 UTC, benmccann commented
Looks like it's passing now

2017-06-23 15:58 UTC, ignasi35 approved these changes

2017-06-23 15:59 UTC, ignasi35 commented
@fsat @edwardcallahan I'm good with merging this unless you think there's any blocker.

2017-06-23 20:44 UTC, edwardcallahan commented
no concerns here, thanks @ignasi35

2017-06-23 23:25 UTC, merged

2017-06-23 23:26 UTC, ignasi35 commented
Thanks @benmccann for your patience.